import fs from "node:fs";
import path from "node:path";
import { GENERATED_DIR, REGISTRY_FILE } from "./paths";

/** Write a generated scene to packages/video/src/scenes/generated/<id>.tsx */
export function writeSceneFile(id: string, code: string): string {
  fs.mkdirSync(GENERATED_DIR, { recursive: true });
  const file = path.join(GENERATED_DIR, `${id}.tsx`);
  fs.writeFileSync(file, code.endsWith("\n") ? code : `${code}\n`, "utf8");
  return file;
}

/** A safe JS identifier derived from a scene id. */
function ident(id: string): string {
  return id.replace(/[^a-zA-Z0-9]/g, "_").replace(/^([0-9])/, "_$1");
}

export function listGeneratedScenes(): string[] {
  if (!fs.existsSync(GENERATED_DIR)) return [];
  return fs
    .readdirSync(GENERATED_DIR)
    .filter((f) => f.endsWith(".tsx"))
    .map((f) => f.replace(/\.tsx$/, ""))
    .sort();
}

/**
 * Rewrite the scene registry from whatever scene files currently exist in
 * generated/. Called after the agent writes scenes so the bundle picks them up.
 */
export function regenerateRegistry(): string[] {
  const ids = listGeneratedScenes();

  // Index-prefix the binding names so ids that normalize to the same identifier
  // (e.g. "foo-bar" vs "foo.bar") can't produce duplicate declarations. Registry
  // keys still use the raw id, which is unique per file.
  const imports = ids
    .map((id, i) => {
      const v = `${i}_${ident(id)}`;
      return `import Scene_${v}, { schema as schema_${v} } from "./generated/${id}";`;
    })
    .join("\n");

  const entries = ids
    .map((id, i) => {
      const v = `${i}_${ident(id)}`;
      return `  ${JSON.stringify(id)}: { id: ${JSON.stringify(id)}, Component: Scene_${v}, schema: schema_${v} },`;
    })
    .join("\n");

  const content = `/**
 * AUTO-GENERATED by @autodemo/cli — do not edit by hand.
 * Maps scene id -> { Component, schema } for ReleaseDemo to look up.
 */
import type { ComponentType } from "react";
import type { ZodTypeAny } from "zod";

${imports || "// (no scenes generated yet)"}

export type SceneEntry = {
  id: string;
  Component: ComponentType<any>;
  schema: ZodTypeAny;
};

export const SCENE_REGISTRY: Record<string, SceneEntry> = {
${entries}
};

export const SCENE_IDS = Object.keys(SCENE_REGISTRY);
`;

  fs.writeFileSync(REGISTRY_FILE, content, "utf8");
  return ids;
}
