/**
 * AUTO-GENERATED by @autodemo/cli — do not edit by hand.
 * Maps scene id -> { Component, schema } for ReleaseDemo to look up.
 */
import type { ComponentType } from "react";
import type { ZodTypeAny } from "zod";

import Scene_0_dark_mode_toggle, { schema as schema_0_dark_mode_toggle } from "./generated/dark-mode-toggle";
import Scene_1_invite_members, { schema as schema_1_invite_members } from "./generated/invite-members";

export type SceneEntry = {
  id: string;
  Component: ComponentType<any>;
  schema: ZodTypeAny;
};

export const SCENE_REGISTRY: Record<string, SceneEntry> = {
  "dark-mode-toggle": { id: "dark-mode-toggle", Component: Scene_0_dark_mode_toggle, schema: schema_0_dark_mode_toggle },
  "invite-members": { id: "invite-members", Component: Scene_1_invite_members, schema: schema_1_invite_members },
};

export const SCENE_IDS = Object.keys(SCENE_REGISTRY);
